version: '3.8'
services:
  client:
    build:
      context: ..
      dockerfile: docker/client.dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "../client:/app/client"
    environment:
      - DEV_ENV=docker
      - NODE_ENV=development

  server:
    build:
      context: ..
      dockerfile: docker/server.dev.Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - "../server:/app/server"
    env_file:
      - ../server/.env.development
